"use client";
import { useRouter } from "next/navigation";
export default function Login(){
  const r=useRouter();
  return (<main className="min-h-screen bg-[#050508] text-white grid lg:grid-cols-2 relative overflow-hidden">
    <div className="absolute inset-0 bg-gradient-to-br from-[#CE1126]/10 via-transparent to-[#008C51]/10 blur-[100px]"/>
    <div className="relative p-10 lg:p-16 flex flex-col justify-between"><a href="/" className="flex items-center gap-3"><div className="h-10 w-10 rounded-full bg-white text-black font-black grid place-items-center">K</div><b>TRACKER KE</b></a>
    <div className="max-w-[420px] mx-auto w-full"><h1 className="text-[56px] font-black tracking-[-0.05em] leading-[0.85]">Welcome<br/><span className="text-white/20">back.</span></h1><form onSubmit={(e:any)=>{e.preventDefault(); const d=new FormData(e.target); const users=JSON.parse(localStorage.getItem("pt_users")||"[]"); const email=d.get("email"); const u=users.find((x:any)=>x.email===email)||{name:"Hon.",email}; localStorage.setItem("pt_session", JSON.stringify(u)); r.push("/dashboard");}} className="mt-10 space-y-4"><input name="email" required placeholder="Email" className="w-full h-[56px] px-6 rounded-full bg-white/[0.06] border border-white/10 outline-none focus:border-white/30"/><input name="password" required type="password" placeholder="Password" className="w-full h-[56px] px-6 rounded-full bg-white/[0.06] border border-white/10 outline-none"/><button className="w-full h-[56px] rounded-full bg-white text-black font-black shadow-[0_0_30px_rgba(255,255,255,0.3)]">Login →</button></form><p className="text-center text-white/30 mt-6 text-sm">No account? <a href="/register" className="text-white font-bold underline">Claim profile</a></p></div><p className="text-[10px] tracking-widest text-white/20">SPECIAL EDITION • VERCEL</p></div>
    <div className="hidden lg:grid place-items-center bg-[#0A0A0D] border-l border-white/5 relative"><div className="w-[380px] rounded-[32px] bg-gradient-to-b from-white/10 to-white/5 border border-white/10 p-2 backdrop-blur-2xl"><div className="rounded-[24px] bg-black p-6"><div className="h-12 w-12 rounded-full bg-gradient-to-br from-[#CE1126] to-[#008C51]"/><p className="mt-6 font-black text-xl">The future of Kenyan politics is data.</p><p className="text-white/40 text-sm mt-2 leading-6">Used by Nation, Citizen, The Star and 12k+ politicians.</p></div></div></div>
  </main>)
}
