"use client";
import { useEffect, useState } from "react";
import { supabase } from "../lib/supabase";
import Link from "next/link";
export default function Home(){
  const [users,setUsers]=useState<any[]>([]);
  const [q,setQ]=useState("");
  useEffect(()=>{ (async()=>{ const {data}=await supabase.from("politicians").select("*").eq("verified",true).order("created_at",{ascending:false}); setUsers(data||[]); })(); },[]);
  const featured = users.filter(u=>u.tier==="featured");
  const filtered = users.filter(u => (u.name||"").toLowerCase().includes(q.toLowerCase()) || (u.county||"").toLowerCase().includes(q.toLowerCase()));
  const adminWa = "https://wa.me/254758973109?text="+encodeURIComponent("Hi, I just paid Till 8629094 on Political Tracker.KE - please verify my payment - 0758973109");
  return (
    <main className="min-h-screen bg-[#050507] text-white">
      <header className="max-w-[1240px] mx-auto px-8 py-7 flex justify-between items-center"><div className="font-black text-[18px]">POLITICAL TRACKER<span className="text-white/30">.KE</span> <span className="text-[10px] ml-2 px-2 py-1 rounded-full bg-[#FFD700] text-black">TILL 8629094</span></div><div className="flex gap-2"><Link href="/register" className="h-11 px-7 rounded-full bg-white text-black font-black text-[13px] grid place-items-center">Register</Link><Link href="/admin" className="h-11 px-6 rounded-full bg-white/10 border border-white/10 text-[13px] grid place-items-center">Admin</Link></div></header>
      <section className="max-w-[1240px] mx-auto px-8 pt-10 pb-10"><h1 className="text-[64px] font-black leading-[0.85]">Find Your<br/><span className="text-white/20">Leader.</span></h1><p className="text-white/40 mt-5 max-w-[560px] text-[14px]">Verified political directory. <span className="text-[#FFD700] font-bold">FEATURED = KES 9,500 Gold</span> • VERIFIED = KES 4,500</p><div className="mt-8 flex gap-3 max-w-[640px]"><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search name, county, party..." className="flex-1 h-[56px] px-6 rounded-full bg-[#121214] border border-white/10 outline-none"/><Link href="/register" className="h-[56px] px-8 rounded-full bg-[#FFD700] text-black font-black text-[13px] grid place-items-center">Get Featured</Link></div></section>
      {featured.length>0 &&!q && (<section className="max-w-[1240px] mx-auto px-8 pb-12"><div className="flex items-center gap-3 mb-5"><div className="h-7 px-4 rounded-full bg-[#FFD700] text-black text-[11px] font-black tracking-widest grid place-items-center">FEATURED • GOLD</div></div><div className="grid grid-cols-1 md:grid-cols-3 gap-4">{featured.map((u:any)=><Link key={u.id} href={`/politician/${u.id}`} className="rounded-[28px] bg-[#FFD700] p-[1px] shadow-[0_0_50px_rgba(255,215,0,0.2)] block hover:scale-[1.02] transition"><div className="rounded-[27px] bg-[#1A1A0A] p-6"><div className="flex justify-between"><div className="font-black text-[18px]">{u.name}</div><span className="text-[8px] px-2 py-1 rounded-full bg-[#FFD700] text-black font-black h-fit">GOLD</span></div><div className="text-[12px] text-white/60 mt-2">{u.role} • {u.county} • {u.party}</div><div className="mt-4 text-[10px] text-[#FFD700]">View Profile →</div></div></Link>)}</div></section>)}
      <section className="max-w-[1240px] mx-auto px-8 pb-28"><div className="grid grid-cols-1 md:grid-cols-3 gap-3">{(q? filtered : users).map((u:any)=><Link key={u.id} href={`/politician/${u.id}`} className={`rounded-[22px] border p-5 block hover:border-white/20 transition ${u.tier==="featured"? "bg-[#FFD700]/5 border-[#FFD700]/20" : "bg-[#121214] border-white/5"}`}><div className="flex justify-between"><div className="font-bold text-[14px]">{u.name}</div>{u.tier==="featured"? <span className="text-[8px] px-2 py-1 rounded-full bg-[#FFD700] text-black font-black h-fit">FEATURED</span> : <span className="text-[8px] px-2 py-1 rounded-full bg-white text-black font-black h-fit">VERIFIED</span>}</div><div className="text-[11px] text-white/40 mt-2">{u.county} • {u.party} • {u.role}</div><div className="text-[10px] text-white/20 mt-3">View Profile →</div></Link>)}{users.length===0 && <div className="col-span-3 rounded-[24px] border border-dashed border-white/10 p-12 text-center text-white/30 text-sm">No verified yet. Be first GOLD.</div>}</div></section>
      <a href={adminWa} target="_blank" className="fixed bottom-6 right-6 h-[56px] px-6 rounded-full bg-[#25D366] text-black font-black text-[13px] flex items-center gap-2 shadow-[0_0_30px_rgba(37,211,102,0.4)] z-50">💬 WhatsApp Admin • Till 8629094 • 0758973109</a>
      <footer className="border-t border-white/5 py-8 text-center text-[11px] text-white/20">Till 8629094 • WhatsApp 0758973109 • KES 0 / 4,500 / 9,500 • Built for Kenya 2026</footer>
    </main>
  )
}