"use client";
import { useEffect, useState } from "react"; import { supabase } from "@/lib/supabase";
export default function Admin(){
  const [users,setUsers]=useState<any[]>([]); const [auth,setAuth]=useState(false); const [pass,setPass]=useState(""); const [q,setQ]=useState("");
  const load = async()=>{ const { data } = await supabase.from("politicians").select("*").order("created_at",{ascending:false}); setUsers(data||[]); };
  useEffect(()=>{ if(auth) load(); },[auth]);
  const approve = async(email:string)=>{ await supabase.from("politicians").update({verified:true}).eq("email",email); load(); };
  const del = async(email:string)=>{ if(!confirm("Delete?")) return; await supabase.from("politicians").delete().eq("email",email); load(); };
  const filtered = users.filter(u=> (u.name||"").toLowerCase().includes(q.toLowerCase()) || (u.email||"").toLowerCase().includes(q.toLowerCase()));
  if(!auth){ return (<main className="min-h-screen bg-[#050508] grid place-items-center p-6"><div className="w-[380px] rounded-[28px] bg-[#121214] border border-white/10 p-8 text-white"><h1 className="text-3xl font-black">Admin</h1><input type="password" value={pass} onChange={e=>setPass(e.target.value)} placeholder="admin123" className="mt-6 w-full h-[56px] px-6 rounded-full bg-white/5 border border-white/10"/><button onClick={()=>setPass(p=>{ if(pass==="admin123") setAuth(true); return p; })} className="mt-4 w-full h-[56px] rounded-full bg-white text-black font-black">Unlock Live DB →</button></div></main>) }
  return (<main className="min-h-screen bg-[#050508] text-white"><nav className="h-[72px] border-b border-white/10 flex items-center justify-between px-8"><span className="font-black">ADMIN • SUPABASE LIVE • {users.length} USERS</span><a href="/" className="h-10 px-5 rounded-full bg-white text-black font-black text-sm grid place-items-center">Live Site</a></nav>
    <div className="max-w-[1400px] mx-auto p-8"><div className="grid grid-cols-3 gap-4"><div className="rounded-[20px] bg-white text-black p-6"><p className="text-xs font-black">TOTAL</p><p className="text-4xl font-black">{users.length}</p></div><div className="rounded-[20px] bg-emerald-500/10 border border-emerald-500/20 p-6"><p className="text-xs font-black text-emerald-400">VERIFIED</p><p className="text-4xl font-black">{users.filter(u=>u.verified).length}</p></div><div className="rounded-[20px] bg-white/5 border border-white/10 p-6"><p className="text-xs">REVENUE</p><p className="text-4xl font-black">KES {(users.filter(u=>u.verified).length*2500).toLocaleString()}</p></div></div>
    <input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search..." className="mt-6 w-full md:w-[400px] h-12 px-6 rounded-full bg-white/5 border border-white/10"/>
    <div className="mt-6 rounded-[24px] bg-[#0E0E11] border border-white/10 overflow-hidden"><table className="w-full text-sm"><thead className="text-white/30 text-xs"><tr><th className="p-4 text-left">NAME</th><th className="p-4 text-left">CONTACT</th><th className="p-4 text-left">COUNTY/PARTY</th><th className="p-4">STATUS</th><th className="p-4">ACTION</th></tr></thead><tbody>{filtered.map((u:any)=><tr key={u.id} className="border-t border-white/5"><td className="p-4 font-bold">{u.name}<div className="text-xs text-white/40">{u.role}</div></td><td className="p-4">{u.email}<div className="text-xs text-white/40">{u.phone}</div></td><td className="p-4">{u.county} • {u.party}</td><td className="p-4">{u.verified?<span className="px-3 py-1 rounded-full bg-emerald-500/20 text-emerald-400 text-xs font-black">VERIFIED</span>:<span className="px-3 py-1 rounded-full bg-amber-500/20 text-amber-400 text-xs">PENDING</span>}</td><td className="p-4 flex gap-2">{!u.verified&&<button onClick={()=>approve(u.email)} className="h-8 px-4 rounded-full bg-white text-black font-black text-xs">Approve</button>}<button onClick={()=>del(u.email)} className="h-8 px-4 rounded-full bg-white/5 border border-white/10 text-xs">Delete</button></td></tr>)}</tbody></table></div></div></main>)
}
