"use client";
import { useEffect, useState } from "react";
import { supabase } from "@/lib/supabase";
export default function Admin(){
  const [users,setUsers]=useState<any[]>([]); const [ok,setOk]=useState(false); const [p,setP]=useState("");
  async function load(){ const {data}=await supabase.from("politicians").select("*").order("created_at",{ascending:false}); setUsers(data||[]); }
  useEffect(()=>{ if(ok) load(); },[ok]);
  if(!ok) return (<main className="min-h-screen bg-black grid place-items-center p-6"><div className="w-[360px] bg-[#121214] border border-white/10 rounded-[24px] p-8 text-white"><h1 className="text-2xl font-black">Admin Login</h1><input type="password" value={p} onChange={e=>setP(e.target.value)} placeholder="admin123" className="mt-6 w-full h-12 px-5 rounded-full bg-white/5 border border-white/10"/><button onClick={()=>{ if(p==="admin123") setOk(true); else alert("wrong"); }} className="mt-4 w-full h-12 rounded-full bg-white text-black font-black">Unlock</button></div></main>);
  return (<main className="min-h-screen bg-black text-white p-8"><div className="flex justify-between items-center"><h1 className="text-3xl font-black">Admin • {users.length} politicians LIVE from Supabase</h1><button onClick={load} className="h-10 px-5 rounded-full bg-white/10">Refresh</button></div><div className="mt-6 grid gap-3">{users.map((u:any)=><div key={u.id} className="p-4 rounded-2xl bg-white/5 border border-white/10 flex justify-between"><div><b>{u.name}</b> - {u.county} • {u.party} • {u.role}<div className="text-xs text-white/40">{u.email} • {u.phone} • {u.tier} {u.verified?"✓ VERIFIED":"PENDING"}</div></div><div className="flex gap-2"><button onClick={async()=>{ await supabase.from("politicians").update({verified:true}).eq("id",u.id); load(); }} className="h-8 px-4 rounded-full bg-white text-black font-black text-xs">Approve</button><button onClick={async()=>{ await supabase.from("politicians").delete().eq("id",u.id); load(); }} className="h-8 px-4 rounded-full bg-red-500/20 text-red-400 text-xs">Delete</button></div></div>)}</div></main>)
}
