"use client";
import { useEffect, useState } from "react"; import { useRouter } from "next/navigation"; import { AreaChart, Area, ResponsiveContainer, Tooltip } from "recharts";
const data=[{v:40},{v:52},{v:48},{v:65},{v:58},{v:72}];
export default function Dashboard(){
  const [user,setUser]=useState<any>(null); const r=useRouter();
  useEffect(()=>{const s=localStorage.getItem("pt_session"); if(!s) r.push("/login"); else setUser(JSON.parse(s));},[]);
  if(!user) return null;
  return (<main className="min-h-screen bg-[#050508] text-white relative overflow-hidden"><div className="absolute inset-0 bg-gradient-to-b from-[#008C51]/10 via-transparent to-[#CE1126]/5 blur-[120px]"/>
    <nav className="relative z-10 h-[72px] border-b border-white/10 bg-black/40 backdrop-blur-2xl flex items-center justify-between px-8"><div className="flex items-center gap-3"><div className="h-9 w-9 rounded-full bg-white text-black font-black grid place-items-center">K</div><span className="font-black">DASHBOARD</span><span className="text-white/20">/ {user.name}</span><span className="ml-3 bg-emerald-500/20 text-emerald-400 text-[10px] px-2 py-1 rounded-full border border-emerald-500/20">● LIVE</span></div><div className="flex gap-2"><a href="/" className="h-10 px-5 grid place-items-center rounded-full bg-white/5 border border-white/10 text-sm">Live Site</a><button onClick={()=>{localStorage.removeItem("pt_session"); r.push("/");}} className="h-10 px-5 rounded-full bg-white text-black font-black text-sm">Logout</button></div></nav>
    <div className="relative z-10 max-w-[1400px] mx-auto px-8 py-12"><h1 className="text-[48px] font-black tracking-tighter leading-[0.9]">Mambo, {user.name?.split(" ")[0]} 👋<br/><span className="text-white/20 font-light">Your influence is rising.</span></h1>
      <div className="grid lg:grid-cols-3 gap-5 mt-12"><div className="rounded-[28px] bg-white text-black p-7 shadow-[0_0_50px_rgba(255,255,255,0.15)]"><p className="text-[11px] tracking-widest opacity-60 font-bold">APPROVAL • SPECIAL</p><p className="text-5xl font-black mt-3">72.4%</p><div className="h-[100px] mt-6"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><Tooltip contentStyle={{background:"#111",border:"1px solid #222",borderRadius:16}}/><Area dataKey="v" stroke="#000" strokeWidth={3} fill="#000" fillOpacity={0.08}/></AreaChart></ResponsiveContainer></div><p className="text-sm font-bold mt-4">▲ +5.2% this week • Rank #3 in Kenya</p></div><div className="rounded-[28px] bg-white/[0.06] border border-white/10 backdrop-blur-xl p-7"><p className="text-[11px] tracking-widest text-white/40">MENTIONS TODAY</p><p className="text-5xl font-black mt-3">2.4k</p><p className="text-emerald-400 font-bold mt-3">↑ 32% • Viral in Nairobi</p><div className="mt-8 flex flex-wrap gap-2"><span className="px-3 py-1.5 rounded-full bg-white text-black text-xs font-bold">#FinanceBill</span><span className="px-3 py-1.5 rounded-full bg-white/10 border border-white/10 text-xs">#Ruto</span></div></div><div className="rounded-[28px] bg-gradient-to-br from-[#CE1126]/20 to-[#008C51]/20 border border-white/10 p-7"><p className="text-[11px] tracking-widest">VERIFICATION STATUS</p><p className="text-2xl font-black mt-3">✅ Special Verified</p><p className="text-white/60 text-sm mt-3 leading-6">You have SPECIAL access. Publish statements, view private county data.</p><button className="mt-8 w-full h-12 rounded-full bg-white text-black font-black">Publish Statement</button></div></div>
      <div className="mt-6 rounded-[28px] bg-white/[0.03] border border-white/10 p-8"><h3 className="font-black text-lg">Your Strongholds • County Breakdown</h3><div className="mt-6 grid md:grid-cols-2 gap-3">{[["Nairobi","82%","🔥 Very High"],["Nakuru","74%","High"],["Mombasa","58%","Medium"],["Kisumu","31%","Low"]].map(([c,p,s])=><div key={c as string} className="flex items-center justify-between p-5 rounded-2xl bg-white/[0.04] border border-white/[0.06] hover:bg-white/[0.06] transition"><span className="font-bold">{c as string}</span><span className="text-sm text-white/50">{s as string}</span><div className="flex items-center gap-3"><div className="w-28 h-2 bg-white/10 rounded-full overflow-hidden"><div className="h-full bg-gradient-to-r from-white to-[#00FF88]" style={{width:p as string}}/></div><span className="font-black text-sm">{p as string}</span></div></div>)}</div></div>
    </div>
  </main>)
}
