"use client";
import { useRouter } from "next/navigation";
export default function Register(){
  const r=useRouter();
  return (<main className="min-h-screen bg-[#050508] text-white grid lg:grid-cols-2 relative overflow-hidden">
    <div className="absolute inset-0 bg-gradient-to-br from-[#008C51]/15 to-[#CE1126]/10 blur-[120px]"/>
    <div className="relative p-10 lg:p-16 flex flex-col justify-between"><a href="/" className="flex items-center gap-3"><div className="h-10 w-10 rounded-full bg-gradient-to-br from-[#CE1126] to-[#008C51] grid place-items-center font-black">K</div><b>TRACKER KE</b><span className="text-[9px] border border-white/20 px-2 py-0.5 rounded-full">SPECIAL</span></a>
    <div className="max-w-[440px] mx-auto w-full"><h1 className="text-[56px] font-black tracking-[-0.05em] leading-[0.85]">Claim your<br/><span className="bg-gradient-to-r from-[#CE1126] to-[#008C51] bg-clip-text text-transparent">power.</span></h1><form onSubmit={(e:any)=>{e.preventDefault(); const d=new FormData(e.target); const users=JSON.parse(localStorage.getItem("pt_users")||"[]"); const u={name:d.get("name"), email:d.get("email")}; users.push(u); localStorage.setItem("pt_users", JSON.stringify(users)); localStorage.setItem("pt_session", JSON.stringify(u)); r.push("/dashboard");}} className="mt-10 space-y-3"><input name="name" required placeholder="Full Name (Hon.)" className="w-full h-[56px] px-6 rounded-full bg-white/[0.06] border border-white/10 outline-none"/><input name="email" required type="email" placeholder="Official Email" className="w-full h-[56px] px-6 rounded-full bg-white/[0.06] border border-white/10 outline-none"/><input name="password" required type="password" placeholder="Create Password" className="w-full h-[56px] px-6 rounded-full bg-white/[0.06] border border-white/10 outline-none"/><button className="w-full h-[56px] rounded-full bg-white text-black font-black text-[15px] shadow-[0_0_40px_rgba(255,255,255,0.3)] mt-2">Create Verified Profile →</button></form><p className="text-center text-white/30 mt-6 text-sm">Have account? <a href="/login" className="text-white font-bold underline">Login</a></p></div><p className="text-[10px] tracking-widest text-white/20">TRUSTED BY 12K+ POLITICIANS</p></div>
    <div className="hidden lg:grid place-items-center bg-[#08080A] border-l border-white/5"><div className="w-[400px] rounded-[36px] bg-white/[0.06] border border-white/10 p-2"><div className="rounded-[28px] bg-[#0F0F12] p-7"><div className="flex items-center gap-3"><div className="h-10 w-10 rounded-full bg-white"/><div><p className="font-bold text-sm">Hon. Verified</p><p className="text-xs text-white/40">Nairobi • Governor</p></div><span className="ml-auto bg-[#008C51]/20 text-[#00FF88] text-[10px] px-2 py-1 rounded-full font-black">VERIFIED ✓</span></div><div className="mt-6 grid grid-cols-2 gap-3"><div className="bg-white text-black rounded-2xl p-4"><p className="text-[10px] opacity-60">SCORE</p><p className="text-2xl font-black">81%</p></div><div className="bg-white/5 border border-white/10 rounded-2xl p-4"><p className="text-[10px] opacity-60">RANK</p><p className="text-2xl font-black">#3 in KE</p></div></div></div></div></div>
  </main>)
}
